#!/bin/bash
dominio="$2"
fun_att () {
apt install ncurses-utils -y > /dev/null 2>&1
mkdir /etc/slowdns > /dev/null 2>&1
cd /etc/slowdns > /dev/null 2>&1
rm * > /dev/null 2>&1
wget https://github.com/egrojlive/slowdns/raw/main/dns-server > /dev/null 2>&1; chmod +x dns-server
wget https://github.com/egrojlive/slowdns/raw/main/remove-slow > /dev/null 2>&1; chmod +x remove-slow
wget https://github.com/egrojlive/slowdns/raw/main/slowdns-info > /dev/null 2>&1; chmod +x slowdns-info
wget https://github.com/egrojlive/slowdns/raw/main/slowdns-drop > /dev/null 2>&1; chmod +x slowdns-drop
wget https://github.com/egrojlive/slowdns/raw/main/slowdns-ssh > /dev/null 2>&1; chmod +x slowdns-ssh
wget https://github.com/egrojlive/slowdns/raw/main/slowdns-ssl > /dev/null 2>&1; chmod +x slowdns-ssl
wget https://github.com/egrojlive/slowdns/raw/main/slowdns-socks > /dev/null 2>&1; chmod +x slowdns-socks
wget https://github.com/egrojlive/slowdns/raw/main/slowdns > /dev/null 2>&1; chmod +x slowdns; cp slowdns /bin/
wget https://github.com/egrojlive/slowdns/raw/main/stopdns > /dev/null 2>&1; chmod +x stopdns
}

fun_ports () {
apt install firewalld -y && sudo firewall-cmd --zone=public --permanent --add-port=80/tcp && sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp && sudo firewall-cmd --zone=public --permanent --add-port=443/tcp && sudo firewall-cmd && sudo firewall-cmd --zone=public --permanent --add-port=53/udp && sudo firewall-cmd --zone=public --permanent --add-port=5300/udp && sudo firewall-cmd && sudo firewall-cmd --zone=public --permanent --add-port=2222/tcp && sudo firewall-cmd --reload
}

fun_dnscf () {
sudo systemctl disable systemd-resolved.service > /dev/null 2>&1 && sudo systemctl stop systemd-resolved.service > /dev/null 2>&1 && sudo mv /etc/resolv.conf /etc/resolv.conf.bkp > /dev/null 2>&1 && echo "nameserver 1.1.1.1" > /etc/resolv.conf
sudo systemctl enable systemd-resolved.service > /dev/null 2>&1 && sudo systemctl start systemd-resolved.service > /dev/null 2>&1
sleep 2
}
echo "Instalando Dependencias..."
fun_att
echo -e "CONFIGURANDO FIREWALL..."
echo ""
#fun_ports
echo "DEFININDO DNS DE CLOUDFLARE..."
echo ""
fun_dnscf
slowdns ssh $dominio
echo ""
cd
rm $0 > /dev/null 2>&1
echo "Instalacion terminada"
echo 'ejecuta slowdns para acceder al menu'
echo
