#!/bin/bash
echo -e "\033[1;36m Esta Es Tu Informacion!\033[0m"
echo ""
echo -ne "SUBDOMINIO NS (Nameserver): " && cat /etc/slowdns/infons
echo ""
echo -ne "KEY: " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://sshplus.net/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m Su Key Se Encuentra En: /root/server.pub\033[0m"
echo -e "\033[1;33mPor Favor Guarda Tu Key!\033[0m"
echo ""
read -p "Presione [Enter] para Salir Del Menu ó CTRL+C para slair"
slowdns