#!/bin/bash
echo "🐧Esta Es Tu Informacion!🐧"
echo ""
echo -ne "🌐SUBDOMINIO NS: " && cat /etc/slowdns/infons
echo ""
echo -ne "🌠KEY: " && cat /root/server.pub
echo ""
echo -ne "👩‍💻COMANDO TERMUX: curl -sO https://sshplus.net/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo "📂Su Key Se Encuentra En: /root/server.pub"
echo "🧰Por Favor Guarda Tu Key!"
echo ""
#read -p "Presione [Enter] para Salir Del Menu ó CTRL+C para slair"
#slowdns
