#!/bin/bash
nameserver="$1"

fun_att () {
apt update > /dev/null 2>&1 && apt upgrade -y > /dev/null 2>&1
}

install_pkgs () {
apt install screen -y > /dev/null 2>&1
apt install cron -y > /dev/null 2>&1
apt install iptables -y > /dev/null 2>&1
service cron reload > /dev/null 2>&1
service cron restart > /dev/null 2>&1
service iptables reload > /dev/null 2>&1
service iptables restart > /dev/null 2>&1
}

ipt_set () {
cd /etc
mv rc.local rc.local.bkp > /dev/null 2>&1
wget https://github.com/leitura/slowdns/raw/main/rc.local > /dev/null 2>&1
chmod +x /etc/rc.local > /dev/null 2>&1
systemctl enable rc-local > /dev/null 2>&1
systemctl start rc-local > /dev/null 2>&1
}

set_ns () {
sleep 1
wget https://github.com/egrojlive/slowdns/raw/main/ssh/startdns > /dev/null 2>&1
wget https://github.com/egrojlive/slowdns/raw/main/ssh/restartdns > /dev/null 2>&1
chmod +x startdns > /dev/null 2>&1
chmod +x restartdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /etc/slowdns/startdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /etc/slowdns/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
}

key () {
restaurar_key
}

restaurar_key() {
echo "Restaurando key existente..." && sleep 2 && echo "OK!"
echo ""
echo "FINALIZANDO..."
finish_ist () {
cd /etc/slowdns
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
}
finish_ist
echo ""
echo "NameServer: " && cat /etc/slowdns/infons
echo ""
echo "Key: " && cat /root/server.pub
echo ""
echo "COMANDO TERMUX: curl -sO https://sshplus.net/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo "Tu Key Se Encuentra En: /root/server.pub"
echo ""
}

nueva_key() {
cd
rm server.key server.pub
echo "Generando nueva key"
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
finish_ist
echo "NameServer: " && cat /etc/slowdns/infons
echo ""
echo "Key: " && cat /root/server.pub
echo ""
echo "COMANDO TERMUX: curl -sO https://sshplus.net/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo "Tu Key Se Encuentra En: /root/server.pub"
echo ""
}

Opcao3 () {
echo "Baixando par de chaves padrão..."
cd
rm server.key server.pub
wget https://github.com/egrojlive/slowdns/raw/main/server.key
wget https://github.com/egrojlive/slowdns/raw/main/server.pub
sleep 1
echo -e "Download Concluído"
sleep 1
cd /etc/slowdns/
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
finish_ist
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://sshplus.net/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m SUA KEY está salva no arquivo /root/server.pub\033[0m"
echo -e "\033[1;33mGuarde-a em um local seguro, pode precisar no futuro!\033[0m"
echo ""
read -p "Pressione [Enter] para voltar ao menu ou CTRL+C para sair"
slowdns
}

OpcaoX () {
exit
}

key_gen () {
echo "Como deseja obter sua key?"
echo ""
echo "[ 1 ] | Gerar na instalação"
echo "[ 2 ] | Usar a key padrão"
echo "[ x ] | Abortar instalação"
echo ""
echo -ne "Digite uma opção: " && read opc_key
case $opc_key in
1) opc_key1 ;;
2) opc_key2 ;;
x) opc_keyx ;;
*) "Comando desconhecido" ; echo ; key_gen;;
esac
}

opc_key1 () {
echo "Gerando sua key..."
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
finish_ist
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://sshplus.net/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m SUA KEY está salva no arquivo /root/server.pub\033[0m"
echo -e "\033[1;33mGuarde-a em um local seguro, pode precisar no futuro!\033[0m"
echo ""
read -p "Pressione [Enter] para voltar ao menu ou CTRL+C para sair"
slowdns
}

opc_key2 () {
echo -e "Baixando par de chaves padrão..."
cd
wget https://github.com/egrojlive/slowdns/raw/main/server.key
wget https://github.com/egrojlive/slowdns/raw/main/server.pub
sleep 1
echo -e "Download Concluído"
sleep 1
cd /etc/slowdns/
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
finish_ist
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://sshplus.net/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m SUA KEY está salva no arquivo /root/server.pub\033[0m"
echo -e "\033[1;33mGuarde-a em um local seguro, pode precisar no futuro!\033[0m"
echo ""
read -p "Pressione [Enter] para voltar ao menu ou CTRL+C para sair"
slowdns
}

opc_keyx () {
echo "Abortando instalação"
sleep 2
slowdns
}

fun_att
echo "Instalando Paquetes Necesarios..."
install_pkgs
echo "Configurando Iptables..."
ipt_set
cd /etc/slowdns
touch infons > /dev/null 2>&1
echo $nameserver > infons
set_ns
echo ""
echo "Verificando Key Existente"
sleep 2
echo ""
sleep 2
cd
key1="/root/server.key"
key2="/root/server.pub"
if [ -f $key1 ] && [ -f $key2 ]
then
echo "Key Encontrada!"
sleep 1
echo ""
key
else
echo "Generando Una Nueva Key"
echo ""
nueva_key
fi
