#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mEspera Por Favor \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mEspera Por Favor \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m Listo !\033[1;37m"
tput cnorm
}
clear
echo -e "\033[1;33mAtencion!\033[0m"
echo ""
echo -e "Al Finalizar La Instalacion Sera Necesario Iniciar"
echo -e "Nuevamente El Servicio de SlowDNS, Escribe Una Opcion"
echo -e "Usar Key Actual"
echo ""
read -p "Presione [ENTER] para continuar o CTRL + C para cancelar"
echo ""
echo -e "   \033[0;36mREMOVIENDO ARCHIVOS ANTIGUOS...\033[0m"
echo ""
fun_remove () {
rm -rf remove-slow; wget https://raw.githubusercontent.com/leitura/slowdns/main/remove-slow && chmod +x remove-slow && bash remove-slow
sleep 2
rm -rf /bin/slowdns && rm /root/remove-slow
sleep 2
rm remove-slow && rm -rf /etc/slowdns
}
fun_bar 'fun_remove'
rm -rf /etc/slowdns
echo ""
echo -e "   \033[0;36mACTUALIZANDO SCRIPT...\033[0m"
echo ""
fun_update () {
rm -rf install && wget https://raw.githubusercontent.com/leitura/slowdns/main/install && chmod +x install && bash install
}
fun_bar 'fun_update'
sleep 3
echo ""
echo -e "\033[0;36mSLOWDNS ATUALIZADO COM CORRECTAMENTE! [✔]\033[0m"
echo ""
sleep 3
echo -e "  \033[1;33mPARA ABRIR EL MENU ESCRIBA: \033[1;37m\033sslowdns\033[1;33m"
echo ""
read -p "Pulsa [ ENTER ] para Salir"
echo -e "\033[0m"